# Generated by Django 6.1.1 on 2026-09-10 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterorder',
            options={'verbose_name': 'gallon purchase', 'verbose_name_plural': 'gallon purchases'},
        ),
        migrations.AddField(
            model_name='gallon',
            name='color',
            field=models.CharField(choices=[('BLUE', 'Blue'), ('PINK', 'Pink')], default='BLUE', max_length=10),
        ),
        migrations.AlterField(
            model_name='waterorder',
            name='distributed_at',
            field=models.DateTimeField(verbose_name='purchase date'),
        ),
        migrations.AlterField(
            model_name='waterorder',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='water.participant', verbose_name='assigned buyer'),
        ),
    ]
