# Generated by Django 6.1.1 on 2026-09-10 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_alter_waterorder_options_gallon_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallon',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallons', to='water.waterorder'),
        ),
        migrations.AlterField(
            model_name='paymentstatushistory',
            name='gallon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='water.gallon'),
        ),
    ]
